version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: kirana_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
